spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unified_login_system
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

logging:
  level:
    root: info    # ????????info
    com.imyuanxiao.unifiedloginsystem: debug    # ??com.imyuanxiao????????debug

